name: build

on: [push, pull_request]

env:
  rust_toolchain: nightly

jobs:
  compile:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Remove `rust-toolchain.toml`
        run: rm rust-toolchain.toml
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install libclang
        run: sudo apt update && sudo apt-get install clang libclang-dev -y
      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.rust_toolchain }}
          components: rustfmt, clippy #, rust-src
          default: true
      - name: Setup | Std
        run: rustup component add rust-src --toolchain ${{ env.rust_toolchain }}-x86_64-unknown-linux-gnu
      - name: Install `ldproxy`
        uses: actions-rs/install@v0.1
        with:
          crate: ldproxy
          version: latest
          use-tool-cache: true
      - name: Format check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      # - name: Build | Clippy
      #   run: cargo clippy --features nightly,experimental --no-deps --target riscv32imc-esp-espidf -Zbuild-std=std,panic_abort -Zbuild-std-features=panic_immediate_abort -- -Dwarnings
      #   continue-on-error: true
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --no-deps --target riscv32imc-esp-espidf -Zbuild-std=std,panic_abort -Zbuild-std-features=panic_immediate_abort -- -Dwarnings
      # - name: Build | Compile
      #   run: cargo build --target riscv32imc-esp-espidf -Zbuild-std=std,panic_abort -Zbuild-std-features=panic_immediate_abort
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target riscv32imc-esp-espidf -Zbuild-std=std,panic_abort -Zbuild-std-features=panic_immediate_abort
