name: publish

on: [release]

env:
  rust_toolchain: nightly

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.rust_toolchain }}
          components: rustfmt, clippy, rust-src
          default: true
      # - name: Setup | Std
      #   run: rustup component add rust-src --toolchain ${{ env.rust_toolchain }}-x86_64-unknown-linux-gnu
      # - name: Setup | Default to nightly
      #   run: rustup default ${{ env.rust_toolchain }}
      - name: Publish
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --dry-run #--token ${{ secrets.CARGO_TOKEN }}